[2024-11-18T17:49:52.167+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-18T17:49:52.263+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_dag.spark_job manual__2024-11-18T17:45:51.665831+00:00 [queued]>
[2024-11-18T17:49:52.401+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_dag.spark_job manual__2024-11-18T17:45:51.665831+00:00 [queued]>
[2024-11-18T17:49:52.404+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-18T17:49:52.601+0000] {taskinstance.py:2330} INFO - Executing <Task(SparkSubmitOperator): spark_job> on 2024-11-18 17:45:51.665831+00:00
[2024-11-18T17:49:52.713+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'spark_dag', 'spark_job', 'manual__2024-11-18T17:45:51.665831+00:00', '--job-id', '666', '--raw', '--subdir', 'DAGS_FOLDER/spark_dag.py', '--cfg-path', '/tmp/tmpluyqr64k']
[2024-11-18T17:49:52.719+0000] {standard_task_runner.py:91} INFO - Job 666: Subtask spark_job
[2024-11-18T17:49:52.709+0000] {standard_task_runner.py:64} INFO - Started process 1774 to run task
[2024-11-18T17:49:52.929+0000] {task_command.py:426} INFO - Running <TaskInstance: spark_dag.spark_job manual__2024-11-18T17:45:51.665831+00:00 [running]> on host 3fa30a842a1c
[2024-11-18T17:49:53.260+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spark_dag' AIRFLOW_CTX_TASK_ID='spark_job' AIRFLOW_CTX_EXECUTION_DATE='2024-11-18T17:45:51.665831+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-18T17:45:51.665831+00:00'
[2024-11-18T17:49:53.267+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-18T17:49:53.289+0000] {base.py:84} INFO - Using connection ID 'spark_default' for task execution.
[2024-11-18T17:49:53.296+0000] {spark_submit.py:473} INFO - Spark-Submit cmd: spark-submit --master spark://spark:7077 --name arrow-spark --deploy-mode client /opt/***/dags/spark_job.py
[2024-11-18T17:50:21.911+0000] {spark_submit.py:634} INFO - 24/11/18 17:50:21 INFO SparkContext: Running Spark version 3.5.3
[2024-11-18T17:50:21.913+0000] {spark_submit.py:634} INFO - 24/11/18 17:50:21 INFO SparkContext: OS info Linux, 5.15.153.1-microsoft-standard-WSL2, amd64
[2024-11-18T17:50:21.953+0000] {spark_submit.py:634} INFO - 24/11/18 17:50:21 INFO SparkContext: Java version 17.0.12
[2024-11-18T17:50:22.676+0000] {spark_submit.py:634} INFO - 24/11/18 17:50:22 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-11-18T17:50:22.832+0000] {job.py:218} ERROR - Job heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/jobs/job.py", line 192, in heartbeat
    self._merge_from(Job._fetch_from_db(self, session))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/api_internal/internal_api_call.py", line 115, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/retries.py", line 89, in wrapped_function
    for attempt in run_with_db_retries(max_retries=retries, logger=logger, **retry_kwargs):
  File "/home/airflow/.local/lib/python3.11/site-packages/tenacity/__init__.py", line 443, in __iter__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/tenacity/__init__.py", line 418, in exc_check
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/tenacity/__init__.py", line 185, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/retries.py", line 98, in wrapped_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/jobs/job.py", line 316, in _fetch_from_db
    session.merge(job)
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 3056, in merge
    return self._merge(
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 3136, in _merge
    merged = self.get(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2853, in get
    return self._get_impl(
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2975, in _get_impl
    return db_load_fn(
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-11-18T17:50:22.943+0000] {job.py:226} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
[2024-11-18T17:51:02.320+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:02 INFO ResourceUtils: ==============================================================
[2024-11-18T17:51:02.325+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:02 INFO ResourceUtils: No custom resources configured for spark.driver.
[2024-11-18T17:51:02.352+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:02 INFO ResourceUtils: ==============================================================
[2024-11-18T17:51:02.354+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:02 INFO SparkContext: Submitted application: Airflow Spark Job
[2024-11-18T17:51:02.677+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:02 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2024-11-18T17:51:02.724+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:02 INFO ResourceProfile: Limiting resource is cpu
[2024-11-18T17:51:02.727+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:02 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2024-11-18T17:51:03.473+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:03 INFO SecurityManager: Changing view acls to: ***
[2024-11-18T17:51:03.478+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:03 INFO SecurityManager: Changing modify acls to: ***
[2024-11-18T17:51:03.481+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:03 INFO SecurityManager: Changing view acls groups to:
[2024-11-18T17:51:03.493+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:03 INFO SecurityManager: Changing modify acls groups to:
[2024-11-18T17:51:03.504+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:03 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: ***; groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY
[2024-11-18T17:51:06.513+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:06 INFO Utils: Successfully started service 'sparkDriver' on port 43471.
[2024-11-18T17:51:06.862+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:06 INFO SparkEnv: Registering MapOutputTracker
[2024-11-18T17:51:07.337+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:07 INFO SparkEnv: Registering BlockManagerMaster
[2024-11-18T17:51:07.656+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:07 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2024-11-18T17:51:07.681+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:07 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2024-11-18T17:51:07.739+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:07 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2024-11-18T17:51:07.962+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:07 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-d474ae28-ef09-468f-a7c0-86ed184cd390
[2024-11-18T17:51:08.055+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:08 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2024-11-18T17:51:08.134+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:08 INFO SparkEnv: Registering OutputCommitCoordinator
[2024-11-18T17:51:16.160+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:16 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2024-11-18T17:51:17.943+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:17 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2024-11-18T17:51:21.100+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:21 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2024-11-18T17:51:22.302+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:22 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master spark:7077
[2024-11-18T17:51:22.303+0000] {spark_submit.py:634} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2024-11-18T17:51:22.306+0000] {spark_submit.py:634} INFO - at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:56)
[2024-11-18T17:51:22.309+0000] {spark_submit.py:634} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
[2024-11-18T17:51:22.310+0000] {spark_submit.py:634} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2024-11-18T17:51:22.312+0000] {spark_submit.py:634} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
[2024-11-18T17:51:22.313+0000] {spark_submit.py:634} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
[2024-11-18T17:51:22.314+0000] {spark_submit.py:634} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:108)
[2024-11-18T17:51:22.314+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[2024-11-18T17:51:22.315+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2024-11-18T17:51:22.316+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2024-11-18T17:51:22.316+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2024-11-18T17:51:22.317+0000] {spark_submit.py:634} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2024-11-18T17:51:22.318+0000] {spark_submit.py:634} INFO - Caused by: java.io.IOException: Failed to connect to spark/172.19.0.4:7077
[2024-11-18T17:51:22.319+0000] {spark_submit.py:634} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:294)
[2024-11-18T17:51:22.329+0000] {spark_submit.py:634} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:214)
[2024-11-18T17:51:22.331+0000] {spark_submit.py:634} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:226)
[2024-11-18T17:51:22.331+0000] {spark_submit.py:634} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2024-11-18T17:51:22.333+0000] {spark_submit.py:634} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2024-11-18T17:51:22.335+0000] {spark_submit.py:634} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2024-11-18T17:51:22.336+0000] {spark_submit.py:634} INFO - ... 4 more
[2024-11-18T17:51:22.337+0000] {spark_submit.py:634} INFO - Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: spark/172.19.0.4:7077
[2024-11-18T17:51:22.338+0000] {spark_submit.py:634} INFO - Caused by: java.net.ConnectException: Connection refused
[2024-11-18T17:51:22.339+0000] {spark_submit.py:634} INFO - at java.base/sun.nio.ch.Net.pollConnect(Native Method)
[2024-11-18T17:51:22.341+0000] {spark_submit.py:634} INFO - at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
[2024-11-18T17:51:22.342+0000] {spark_submit.py:634} INFO - at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:946)
[2024-11-18T17:51:22.343+0000] {spark_submit.py:634} INFO - at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
[2024-11-18T17:51:22.344+0000] {spark_submit.py:634} INFO - at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
[2024-11-18T17:51:22.345+0000] {spark_submit.py:634} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
[2024-11-18T17:51:22.346+0000] {spark_submit.py:634} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
[2024-11-18T17:51:22.346+0000] {spark_submit.py:634} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
[2024-11-18T17:51:22.347+0000] {spark_submit.py:634} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
[2024-11-18T17:51:22.348+0000] {spark_submit.py:634} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[2024-11-18T17:51:22.351+0000] {spark_submit.py:634} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2024-11-18T17:51:22.352+0000] {spark_submit.py:634} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2024-11-18T17:51:22.358+0000] {spark_submit.py:634} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2024-11-18T17:51:41.085+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:41 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2024-11-18T17:51:41.090+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:41 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master spark:7077
[2024-11-18T17:51:41.091+0000] {spark_submit.py:634} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2024-11-18T17:51:41.091+0000] {spark_submit.py:634} INFO - at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:56)
[2024-11-18T17:51:41.092+0000] {spark_submit.py:634} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
[2024-11-18T17:51:41.092+0000] {spark_submit.py:634} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2024-11-18T17:51:41.092+0000] {spark_submit.py:634} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
[2024-11-18T17:51:41.093+0000] {spark_submit.py:634} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
[2024-11-18T17:51:41.093+0000] {spark_submit.py:634} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:108)
[2024-11-18T17:51:41.094+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[2024-11-18T17:51:41.094+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2024-11-18T17:51:41.095+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2024-11-18T17:51:41.095+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2024-11-18T17:51:41.095+0000] {spark_submit.py:634} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2024-11-18T17:51:41.096+0000] {spark_submit.py:634} INFO - Caused by: java.io.IOException: Failed to connect to spark/172.19.0.4:7077
[2024-11-18T17:51:41.096+0000] {spark_submit.py:634} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:294)
[2024-11-18T17:51:41.096+0000] {spark_submit.py:634} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:214)
[2024-11-18T17:51:41.096+0000] {spark_submit.py:634} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:226)
[2024-11-18T17:51:41.097+0000] {spark_submit.py:634} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2024-11-18T17:51:41.097+0000] {spark_submit.py:634} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2024-11-18T17:51:41.097+0000] {spark_submit.py:634} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2024-11-18T17:51:41.097+0000] {spark_submit.py:634} INFO - ... 4 more
[2024-11-18T17:51:41.097+0000] {spark_submit.py:634} INFO - Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: spark/172.19.0.4:7077
[2024-11-18T17:51:41.098+0000] {spark_submit.py:634} INFO - Caused by: java.net.ConnectException: Connection refused
[2024-11-18T17:51:41.098+0000] {spark_submit.py:634} INFO - at java.base/sun.nio.ch.Net.pollConnect(Native Method)
[2024-11-18T17:51:41.098+0000] {spark_submit.py:634} INFO - at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
[2024-11-18T17:51:41.098+0000] {spark_submit.py:634} INFO - at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:946)
[2024-11-18T17:51:41.098+0000] {spark_submit.py:634} INFO - at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
[2024-11-18T17:51:41.099+0000] {spark_submit.py:634} INFO - at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
[2024-11-18T17:51:41.099+0000] {spark_submit.py:634} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
[2024-11-18T17:51:41.099+0000] {spark_submit.py:634} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
[2024-11-18T17:51:41.099+0000] {spark_submit.py:634} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
[2024-11-18T17:51:41.099+0000] {spark_submit.py:634} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
[2024-11-18T17:51:41.099+0000] {spark_submit.py:634} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[2024-11-18T17:51:41.100+0000] {spark_submit.py:634} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2024-11-18T17:51:41.100+0000] {spark_submit.py:634} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2024-11-18T17:51:41.100+0000] {spark_submit.py:634} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2024-11-18T17:52:01.577+0000] {spark_submit.py:634} INFO - 24/11/18 17:52:01 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2024-11-18T17:52:03.104+0000] {spark_submit.py:634} INFO - 24/11/18 17:52:03 INFO TransportClientFactory: Successfully created connection to spark/172.19.0.8:7077 after 16 ms (0 ms spent in bootstraps)
[2024-11-18T17:52:04.265+0000] {spark_submit.py:634} INFO - 24/11/18 17:52:04 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20241118175204-0001
[2024-11-18T17:52:04.431+0000] {spark_submit.py:634} INFO - 24/11/18 17:52:04 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 46829.
[2024-11-18T17:52:04.433+0000] {spark_submit.py:634} INFO - 24/11/18 17:52:04 INFO NettyBlockTransferService: Server created on 3fa30a842a1c:46829
[2024-11-18T17:52:04.437+0000] {spark_submit.py:634} INFO - 24/11/18 17:52:04 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2024-11-18T17:52:04.532+0000] {spark_submit.py:634} INFO - 24/11/18 17:52:04 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 3fa30a842a1c, 46829, None)
[2024-11-18T17:52:04.566+0000] {spark_submit.py:634} INFO - 24/11/18 17:52:04 INFO BlockManagerMasterEndpoint: Registering block manager 3fa30a842a1c:46829 with 434.4 MiB RAM, BlockManagerId(driver, 3fa30a842a1c, 46829, None)
[2024-11-18T17:52:04.572+0000] {spark_submit.py:634} INFO - 24/11/18 17:52:04 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 3fa30a842a1c, 46829, None)
[2024-11-18T17:52:04.579+0000] {spark_submit.py:634} INFO - 24/11/18 17:52:04 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 3fa30a842a1c, 46829, None)
[2024-11-18T17:52:50.375+0000] {spark_submit.py:634} INFO - 24/11/18 17:52:50 INFO AsyncEventQueue: Process of event SparkListenerExecutorMetricsUpdate(driver,WrappedArray(),Map((-1,-1) -> org.apache.spark.executor.ExecutorMetrics@1c143fb8)) by listener AppStatusListener took 8.724771751s.
[2024-11-18T17:52:53.859+0000] {spark_submit.py:634} INFO - 24/11/18 17:52:50 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2024-11-18T17:52:53.499+0000] {job.py:226} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
[2024-11-18T17:54:25.588+0000] {job.py:226} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
[2024-11-18T17:54:35.233+0000] {spark_submit.py:634} INFO - 24/11/18 17:54:34 INFO AsyncEventQueue: Process of event SparkListenerExecutorMetricsUpdate(driver,WrappedArray(),Map((-1,-1) -> org.apache.spark.executor.ExecutorMetrics@f159221)) by listener AppStatusListener took 1.65532871s.
[2024-11-18T17:54:49.201+0000] {spark_submit.py:634} INFO - 24/11/18 17:54:49 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2024-11-18T17:54:49.430+0000] {spark_submit.py:634} INFO - 24/11/18 17:54:49 INFO SharedState: Warehouse path is 'file:/app/spark-warehouse'.
[2024-11-18T17:55:13.664+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:13 INFO CodeGenerator: Code generated in 718.570917 ms
[2024-11-18T17:55:13.855+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:13 INFO SparkContext: Starting job: showString at NativeMethodAccessorImpl.java:0
[2024-11-18T17:55:13.932+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:13 INFO DAGScheduler: Got job 0 (showString at NativeMethodAccessorImpl.java:0) with 1 output partitions
[2024-11-18T17:55:13.963+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:13 INFO DAGScheduler: Final stage: ResultStage 0 (showString at NativeMethodAccessorImpl.java:0)
[2024-11-18T17:55:13.971+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:13 INFO DAGScheduler: Parents of final stage: List()
[2024-11-18T17:55:13.975+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:13 INFO DAGScheduler: Missing parents: List()
[2024-11-18T17:55:14.025+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:14 INFO DAGScheduler: Submitting ResultStage 0 (MapPartitionsRDD[6] at showString at NativeMethodAccessorImpl.java:0), which has no missing parents
[2024-11-18T17:55:14.433+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:14 INFO MemoryStore: Block broadcast_0 stored as values in memory (estimated size 13.1 KiB, free 434.4 MiB)
[2024-11-18T17:55:14.722+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:14 INFO MemoryStore: Block broadcast_0_piece0 stored as bytes in memory (estimated size 6.8 KiB, free 434.4 MiB)
[2024-11-18T17:55:14.736+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:14 INFO BlockManagerInfo: Added broadcast_0_piece0 in memory on 3fa30a842a1c:46829 (size: 6.8 KiB, free: 434.4 MiB)
[2024-11-18T17:55:14.740+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:14 INFO SparkContext: Created broadcast 0 from broadcast at DAGScheduler.scala:1585
[2024-11-18T17:55:14.841+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:14 INFO DAGScheduler: Submitting 1 missing tasks from ResultStage 0 (MapPartitionsRDD[6] at showString at NativeMethodAccessorImpl.java:0) (first 15 tasks are for partitions Vector(0))
[2024-11-18T17:55:14.846+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:14 INFO TaskSchedulerImpl: Adding task set 0.0 with 1 tasks resource profile 0
[2024-11-18T17:55:29.877+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:29 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2024-11-18T17:55:30.637+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:30 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20241118175204-0001/0 on worker-20241118175528-172.19.0.10-35337 (172.19.0.10:35337) with 1 core(s)
[2024-11-18T17:55:30.641+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:30 INFO StandaloneSchedulerBackend: Granted executor ID app-20241118175204-0001/0 on hostPort 172.19.0.10:35337 with 1 core(s), 1024.0 MiB RAM
[2024-11-18T17:55:30.646+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:30 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20241118175204-0001/1 on worker-20241118175528-172.19.0.6-33793 (172.19.0.6:33793) with 1 core(s)
[2024-11-18T17:55:30.649+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:30 INFO StandaloneSchedulerBackend: Granted executor ID app-20241118175204-0001/1 on hostPort 172.19.0.6:33793 with 1 core(s), 1024.0 MiB RAM
[2024-11-18T17:55:30.917+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:30 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20241118175204-0001/0 is now RUNNING
[2024-11-18T17:55:30.919+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:30 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20241118175204-0001/1 is now RUNNING
[2024-11-18T17:55:35.536+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:35 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Registered executor NettyRpcEndpointRef(spark-client://Executor) (172.19.0.6:55898) with ID 1,  ResourceProfileId 0
[2024-11-18T17:55:35.547+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:35 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Registered executor NettyRpcEndpointRef(spark-client://Executor) (172.19.0.10:38452) with ID 0,  ResourceProfileId 0
[2024-11-18T17:55:35.727+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:35 INFO BlockManagerMasterEndpoint: Registering block manager 172.19.0.10:46369 with 434.4 MiB RAM, BlockManagerId(0, 172.19.0.10, 46369, None)
[2024-11-18T17:55:35.732+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:35 INFO BlockManagerMasterEndpoint: Registering block manager 172.19.0.6:39013 with 434.4 MiB RAM, BlockManagerId(1, 172.19.0.6, 39013, None)
[2024-11-18T17:55:35.849+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:35 INFO TaskSetManager: Starting task 0.0 in stage 0.0 (TID 0) (172.19.0.6, executor 1, partition 0, PROCESS_LOCAL, 9122 bytes)
[2024-11-18T17:55:35.974+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:35 WARN TaskSetManager: Lost task 0.0 in stage 0.0 (TID 0) (172.19.0.6 executor 1): java.io.InvalidClassException: org.apache.spark.scheduler.Task; local class incompatible: stream classdesc serialVersionUID = -6188971942555435033, local class serialVersionUID = 553100815431272095
[2024-11-18T17:55:35.975+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:597)
[2024-11-18T17:55:35.975+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2051)
[2024-11-18T17:55:35.976+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1898)
[2024-11-18T17:55:35.976+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2051)
[2024-11-18T17:55:35.977+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1898)
[2024-11-18T17:55:35.977+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2224)
[2024-11-18T17:55:35.977+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1733)
[2024-11-18T17:55:35.978+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:509)
[2024-11-18T17:55:35.978+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:467)
[2024-11-18T17:55:35.978+0000] {spark_submit.py:634} INFO - at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:87)
[2024-11-18T17:55:35.978+0000] {spark_submit.py:634} INFO - at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:129)
[2024-11-18T17:55:35.979+0000] {spark_submit.py:634} INFO - at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:579)
[2024-11-18T17:55:35.979+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2024-11-18T17:55:35.979+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2024-11-18T17:55:35.980+0000] {spark_submit.py:634} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2024-11-18T17:55:35.980+0000] {spark_submit.py:634} INFO - 
[2024-11-18T17:55:35.980+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:35 INFO TaskSetManager: Starting task 0.1 in stage 0.0 (TID 1) (172.19.0.6, executor 1, partition 0, PROCESS_LOCAL, 9122 bytes)
[2024-11-18T17:55:35.995+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:35 INFO TaskSetManager: Lost task 0.1 in stage 0.0 (TID 1) on 172.19.0.6, executor 1: java.io.InvalidClassException (org.apache.spark.scheduler.Task; local class incompatible: stream classdesc serialVersionUID = -6188971942555435033, local class serialVersionUID = 553100815431272095) [duplicate 1]
[2024-11-18T17:55:35.998+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:35 INFO TaskSetManager: Starting task 0.2 in stage 0.0 (TID 2) (172.19.0.6, executor 1, partition 0, PROCESS_LOCAL, 9122 bytes)
[2024-11-18T17:55:36.011+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:36 INFO TaskSetManager: Lost task 0.2 in stage 0.0 (TID 2) on 172.19.0.6, executor 1: java.io.InvalidClassException (org.apache.spark.scheduler.Task; local class incompatible: stream classdesc serialVersionUID = -6188971942555435033, local class serialVersionUID = 553100815431272095) [duplicate 2]
[2024-11-18T17:55:36.013+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:36 INFO TaskSetManager: Starting task 0.3 in stage 0.0 (TID 3) (172.19.0.6, executor 1, partition 0, PROCESS_LOCAL, 9122 bytes)
[2024-11-18T17:55:36.024+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:36 INFO TaskSetManager: Lost task 0.3 in stage 0.0 (TID 3) on 172.19.0.6, executor 1: java.io.InvalidClassException (org.apache.spark.scheduler.Task; local class incompatible: stream classdesc serialVersionUID = -6188971942555435033, local class serialVersionUID = 553100815431272095) [duplicate 3]
[2024-11-18T17:55:36.034+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:36 ERROR TaskSetManager: Task 0 in stage 0.0 failed 4 times; aborting job
[2024-11-18T17:55:36.036+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:36 INFO TaskSchedulerImpl: Removed TaskSet 0.0, whose tasks have all completed, from pool
[2024-11-18T17:55:36.037+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:36 INFO TaskSchedulerImpl: Cancelling stage 0
[2024-11-18T17:55:36.038+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:36 INFO TaskSchedulerImpl: Killing all running tasks in stage 0: Stage cancelled: Job aborted due to stage failure: Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 3) (172.19.0.6 executor 1): java.io.InvalidClassException: org.apache.spark.scheduler.Task; local class incompatible: stream classdesc serialVersionUID = -6188971942555435033, local class serialVersionUID = 553100815431272095
[2024-11-18T17:55:36.038+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:597)
[2024-11-18T17:55:36.039+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2051)
[2024-11-18T17:55:36.042+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1898)
[2024-11-18T17:55:36.045+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2051)
[2024-11-18T17:55:36.046+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1898)
[2024-11-18T17:55:36.047+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2224)
[2024-11-18T17:55:36.047+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1733)
[2024-11-18T17:55:36.047+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:509)
[2024-11-18T17:55:36.048+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:467)
[2024-11-18T17:55:36.048+0000] {spark_submit.py:634} INFO - at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:87)
[2024-11-18T17:55:36.048+0000] {spark_submit.py:634} INFO - at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:129)
[2024-11-18T17:55:36.048+0000] {spark_submit.py:634} INFO - at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:579)
[2024-11-18T17:55:36.049+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2024-11-18T17:55:36.049+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2024-11-18T17:55:36.049+0000] {spark_submit.py:634} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2024-11-18T17:55:36.050+0000] {spark_submit.py:634} INFO - 
[2024-11-18T17:55:36.050+0000] {spark_submit.py:634} INFO - Driver stacktrace:
[2024-11-18T17:55:36.050+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:36 INFO DAGScheduler: ResultStage 0 (showString at NativeMethodAccessorImpl.java:0) failed in 21.925 s due to Job aborted due to stage failure: Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 3) (172.19.0.6 executor 1): java.io.InvalidClassException: org.apache.spark.scheduler.Task; local class incompatible: stream classdesc serialVersionUID = -6188971942555435033, local class serialVersionUID = 553100815431272095
[2024-11-18T17:55:36.050+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:597)
[2024-11-18T17:55:36.051+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2051)
[2024-11-18T17:55:36.051+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1898)
[2024-11-18T17:55:36.051+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2051)
[2024-11-18T17:55:36.051+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1898)
[2024-11-18T17:55:36.052+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2224)
[2024-11-18T17:55:36.052+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1733)
[2024-11-18T17:55:36.052+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:509)
[2024-11-18T17:55:36.052+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:467)
[2024-11-18T17:55:36.052+0000] {spark_submit.py:634} INFO - at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:87)
[2024-11-18T17:55:36.053+0000] {spark_submit.py:634} INFO - at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:129)
[2024-11-18T17:55:36.053+0000] {spark_submit.py:634} INFO - at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:579)
[2024-11-18T17:55:36.053+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2024-11-18T17:55:36.053+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2024-11-18T17:55:36.053+0000] {spark_submit.py:634} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2024-11-18T17:55:36.054+0000] {spark_submit.py:634} INFO - 
[2024-11-18T17:55:36.054+0000] {spark_submit.py:634} INFO - Driver stacktrace:
[2024-11-18T17:55:36.054+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:36 INFO DAGScheduler: Job 0 failed: showString at NativeMethodAccessorImpl.java:0, took 22.177240 s
[2024-11-18T17:55:36.442+0000] {spark_submit.py:634} INFO - Traceback (most recent call last):
[2024-11-18T17:55:36.443+0000] {spark_submit.py:634} INFO - File "/opt/***/dags/spark_job.py", line 16, in <module>
[2024-11-18T17:55:36.446+0000] {spark_submit.py:634} INFO - df.show()
[2024-11-18T17:55:36.447+0000] {spark_submit.py:634} INFO - File "/home/***/.local/lib/python3.11/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/dataframe.py", line 947, in show
[2024-11-18T17:55:36.453+0000] {spark_submit.py:634} INFO - File "/home/***/.local/lib/python3.11/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/dataframe.py", line 965, in _show_string
[2024-11-18T17:55:36.454+0000] {spark_submit.py:634} INFO - File "/home/***/.local/lib/python3.11/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
[2024-11-18T17:55:36.454+0000] {spark_submit.py:634} INFO - File "/home/***/.local/lib/python3.11/site-packages/pyspark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 179, in deco
[2024-11-18T17:55:36.455+0000] {spark_submit.py:634} INFO - File "/home/***/.local/lib/python3.11/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/protocol.py", line 326, in get_return_value
[2024-11-18T17:55:36.456+0000] {spark_submit.py:634} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling o41.showString.
[2024-11-18T17:55:36.456+0000] {spark_submit.py:634} INFO - : org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 3) (172.19.0.6 executor 1): java.io.InvalidClassException: org.apache.spark.scheduler.Task; local class incompatible: stream classdesc serialVersionUID = -6188971942555435033, local class serialVersionUID = 553100815431272095
[2024-11-18T17:55:36.457+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:597)
[2024-11-18T17:55:36.457+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2051)
[2024-11-18T17:55:36.458+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1898)
[2024-11-18T17:55:36.458+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2051)
[2024-11-18T17:55:36.458+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1898)
[2024-11-18T17:55:36.459+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2224)
[2024-11-18T17:55:36.460+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1733)
[2024-11-18T17:55:36.460+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:509)
[2024-11-18T17:55:36.460+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:467)
[2024-11-18T17:55:36.461+0000] {spark_submit.py:634} INFO - at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:87)
[2024-11-18T17:55:36.461+0000] {spark_submit.py:634} INFO - at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:129)
[2024-11-18T17:55:36.461+0000] {spark_submit.py:634} INFO - at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:579)
[2024-11-18T17:55:36.462+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2024-11-18T17:55:36.462+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2024-11-18T17:55:36.462+0000] {spark_submit.py:634} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2024-11-18T17:55:36.463+0000] {spark_submit.py:634} INFO - 
[2024-11-18T17:55:36.463+0000] {spark_submit.py:634} INFO - Driver stacktrace:
[2024-11-18T17:55:36.466+0000] {spark_submit.py:634} INFO - at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2856)
[2024-11-18T17:55:36.467+0000] {spark_submit.py:634} INFO - at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2792)
[2024-11-18T17:55:36.467+0000] {spark_submit.py:634} INFO - at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2791)
[2024-11-18T17:55:36.467+0000] {spark_submit.py:634} INFO - at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
[2024-11-18T17:55:36.468+0000] {spark_submit.py:634} INFO - at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
[2024-11-18T17:55:36.468+0000] {spark_submit.py:634} INFO - at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
[2024-11-18T17:55:36.469+0000] {spark_submit.py:634} INFO - at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2791)
[2024-11-18T17:55:36.469+0000] {spark_submit.py:634} INFO - at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1247)
[2024-11-18T17:55:36.469+0000] {spark_submit.py:634} INFO - at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1247)
[2024-11-18T17:55:36.470+0000] {spark_submit.py:634} INFO - at scala.Option.foreach(Option.scala:407)
[2024-11-18T17:55:36.470+0000] {spark_submit.py:634} INFO - at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1247)
[2024-11-18T17:55:36.470+0000] {spark_submit.py:634} INFO - at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:3060)
[2024-11-18T17:55:36.471+0000] {spark_submit.py:634} INFO - at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2994)
[2024-11-18T17:55:36.471+0000] {spark_submit.py:634} INFO - at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2983)
[2024-11-18T17:55:36.472+0000] {spark_submit.py:634} INFO - at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
[2024-11-18T17:55:36.473+0000] {spark_submit.py:634} INFO - at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:989)
[2024-11-18T17:55:36.473+0000] {spark_submit.py:634} INFO - at org.apache.spark.SparkContext.runJob(SparkContext.scala:2393)
[2024-11-18T17:55:36.473+0000] {spark_submit.py:634} INFO - at org.apache.spark.SparkContext.runJob(SparkContext.scala:2414)
[2024-11-18T17:55:36.474+0000] {spark_submit.py:634} INFO - at org.apache.spark.SparkContext.runJob(SparkContext.scala:2433)
[2024-11-18T17:55:36.475+0000] {spark_submit.py:634} INFO - at org.apache.spark.sql.execution.SparkPlan.executeTake(SparkPlan.scala:530)
[2024-11-18T17:55:36.476+0000] {spark_submit.py:634} INFO - at org.apache.spark.sql.execution.SparkPlan.executeTake(SparkPlan.scala:483)
[2024-11-18T17:55:36.476+0000] {spark_submit.py:634} INFO - at org.apache.spark.sql.execution.CollectLimitExec.executeCollect(limit.scala:61)
[2024-11-18T17:55:36.476+0000] {spark_submit.py:634} INFO - at org.apache.spark.sql.Dataset.collectFromPlan(Dataset.scala:4333)
[2024-11-18T17:55:36.476+0000] {spark_submit.py:634} INFO - at org.apache.spark.sql.Dataset.$anonfun$head$1(Dataset.scala:3316)
[2024-11-18T17:55:36.477+0000] {spark_submit.py:634} INFO - at org.apache.spark.sql.Dataset.$anonfun$withAction$2(Dataset.scala:4323)
[2024-11-18T17:55:36.477+0000] {spark_submit.py:634} INFO - at org.apache.spark.sql.execution.QueryExecution$.withInternalError(QueryExecution.scala:546)
[2024-11-18T17:55:36.477+0000] {spark_submit.py:634} INFO - at org.apache.spark.sql.Dataset.$anonfun$withAction$1(Dataset.scala:4321)
[2024-11-18T17:55:36.477+0000] {spark_submit.py:634} INFO - at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:125)
[2024-11-18T17:55:36.477+0000] {spark_submit.py:634} INFO - at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:201)
[2024-11-18T17:55:36.478+0000] {spark_submit.py:634} INFO - at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:108)
[2024-11-18T17:55:36.478+0000] {spark_submit.py:634} INFO - at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:900)
[2024-11-18T17:55:36.478+0000] {spark_submit.py:634} INFO - at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:66)
[2024-11-18T17:55:36.479+0000] {spark_submit.py:634} INFO - at org.apache.spark.sql.Dataset.withAction(Dataset.scala:4321)
[2024-11-18T17:55:36.479+0000] {spark_submit.py:634} INFO - at org.apache.spark.sql.Dataset.head(Dataset.scala:3316)
[2024-11-18T17:55:36.479+0000] {spark_submit.py:634} INFO - at org.apache.spark.sql.Dataset.take(Dataset.scala:3539)
[2024-11-18T17:55:36.479+0000] {spark_submit.py:634} INFO - at org.apache.spark.sql.Dataset.getRows(Dataset.scala:280)
[2024-11-18T17:55:36.480+0000] {spark_submit.py:634} INFO - at org.apache.spark.sql.Dataset.showString(Dataset.scala:315)
[2024-11-18T17:55:36.480+0000] {spark_submit.py:634} INFO - at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2024-11-18T17:55:36.480+0000] {spark_submit.py:634} INFO - at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2024-11-18T17:55:36.480+0000] {spark_submit.py:634} INFO - at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2024-11-18T17:55:36.481+0000] {spark_submit.py:634} INFO - at java.base/java.lang.reflect.Method.invoke(Method.java:569)
[2024-11-18T17:55:36.481+0000] {spark_submit.py:634} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2024-11-18T17:55:36.481+0000] {spark_submit.py:634} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2024-11-18T17:55:36.481+0000] {spark_submit.py:634} INFO - at py4j.Gateway.invoke(Gateway.java:282)
[2024-11-18T17:55:36.482+0000] {spark_submit.py:634} INFO - at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2024-11-18T17:55:36.482+0000] {spark_submit.py:634} INFO - at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2024-11-18T17:55:36.482+0000] {spark_submit.py:634} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2024-11-18T17:55:36.482+0000] {spark_submit.py:634} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2024-11-18T17:55:36.483+0000] {spark_submit.py:634} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2024-11-18T17:55:36.483+0000] {spark_submit.py:634} INFO - Caused by: java.io.InvalidClassException: org.apache.spark.scheduler.Task; local class incompatible: stream classdesc serialVersionUID = -6188971942555435033, local class serialVersionUID = 553100815431272095
[2024-11-18T17:55:36.483+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:597)
[2024-11-18T17:55:36.483+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2051)
[2024-11-18T17:55:36.484+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1898)
[2024-11-18T17:55:36.484+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2051)
[2024-11-18T17:55:36.484+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1898)
[2024-11-18T17:55:36.485+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2224)
[2024-11-18T17:55:36.485+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1733)
[2024-11-18T17:55:36.485+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:509)
[2024-11-18T17:55:36.485+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:467)
[2024-11-18T17:55:36.486+0000] {spark_submit.py:634} INFO - at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:87)
[2024-11-18T17:55:36.486+0000] {spark_submit.py:634} INFO - at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:129)
[2024-11-18T17:55:36.486+0000] {spark_submit.py:634} INFO - at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:579)
[2024-11-18T17:55:36.487+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2024-11-18T17:55:36.487+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2024-11-18T17:55:36.487+0000] {spark_submit.py:634} INFO - ... 1 more
[2024-11-18T17:55:36.487+0000] {spark_submit.py:634} INFO - 
[2024-11-18T17:55:36.968+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:36 INFO SparkContext: Invoking stop() from shutdown hook
[2024-11-18T17:55:36.968+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:36 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2024-11-18T17:55:36.987+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:36 INFO SparkUI: Stopped Spark web UI at http://3fa30a842a1c:4040
[2024-11-18T17:55:36.989+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:36 INFO StandaloneSchedulerBackend: Shutting down all executors
[2024-11-18T17:55:36.990+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:36 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Asking each executor to shut down
[2024-11-18T17:55:37.034+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:37 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2024-11-18T17:55:37.260+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:37 INFO MemoryStore: MemoryStore cleared
[2024-11-18T17:55:37.262+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:37 INFO BlockManager: BlockManager stopped
[2024-11-18T17:55:37.297+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:37 INFO BlockManagerMaster: BlockManagerMaster stopped
[2024-11-18T17:55:37.328+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:37 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2024-11-18T17:55:37.358+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:37 INFO SparkContext: Successfully stopped SparkContext
[2024-11-18T17:55:37.361+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:37 INFO ShutdownHookManager: Shutdown hook called
[2024-11-18T17:55:37.367+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:37 INFO ShutdownHookManager: Deleting directory /tmp/spark-56c78659-5b76-47d1-b9c4-9a890c331735/pyspark-25beea02-c20e-4c86-aa2c-51b4963f28d7
[2024-11-18T17:55:37.374+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:37 INFO ShutdownHookManager: Deleting directory /tmp/spark-56c78659-5b76-47d1-b9c4-9a890c331735
[2024-11-18T17:55:37.381+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:37 INFO ShutdownHookManager: Deleting directory /tmp/spark-51ccfa67-7e32-4332-ad77-ae182099f630
[2024-11-18T17:55:37.462+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-18T17:55:37.494+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 176, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 560, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark:7077 --name arrow-spark --deploy-mode client /opt/***/dags/spark_job.py. Error code is: 1.
[2024-11-18T17:55:37.516+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=spark_dag, task_id=spark_job, run_id=manual__2024-11-18T17:45:51.665831+00:00, execution_date=20241118T174551, start_date=20241118T174952, end_date=20241118T175537
[2024-11-18T17:55:37.555+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 666 for task spark_job (Cannot execute: spark-submit --master spark://spark:7077 --name arrow-spark --deploy-mode client /opt/***/dags/spark_job.py. Error code is: 1.; 1774)
[2024-11-18T17:55:37.586+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-11-18T17:55:37.781+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-18T17:55:37.784+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
