[2024-11-18T17:49:50.881+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-18T17:49:50.975+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spark_dag.spark_job scheduled__2024-11-16T00:00:00+00:00 [queued]>
[2024-11-18T17:49:51.012+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spark_dag.spark_job scheduled__2024-11-16T00:00:00+00:00 [queued]>
[2024-11-18T17:49:51.014+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-11-18T17:49:51.116+0000] {taskinstance.py:2330} INFO - Executing <Task(SparkSubmitOperator): spark_job> on 2024-11-16 00:00:00+00:00
[2024-11-18T17:49:51.149+0000] {standard_task_runner.py:64} INFO - Started process 1681 to run task
[2024-11-18T17:49:51.202+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'spark_dag', 'spark_job', 'scheduled__2024-11-16T00:00:00+00:00', '--job-id', '659', '--raw', '--subdir', 'DAGS_FOLDER/spark_dag.py', '--cfg-path', '/tmp/tmpwsz7dcce']
[2024-11-18T17:49:51.207+0000] {standard_task_runner.py:91} INFO - Job 659: Subtask spark_job
[2024-11-18T17:49:51.439+0000] {task_command.py:426} INFO - Running <TaskInstance: spark_dag.spark_job scheduled__2024-11-16T00:00:00+00:00 [running]> on host 3fa30a842a1c
[2024-11-18T17:49:52.116+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spark_dag' AIRFLOW_CTX_TASK_ID='spark_job' AIRFLOW_CTX_EXECUTION_DATE='2024-11-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-16T00:00:00+00:00'
[2024-11-18T17:49:52.126+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-18T17:49:52.182+0000] {base.py:84} INFO - Using connection ID 'spark_default' for task execution.
[2024-11-18T17:49:52.200+0000] {spark_submit.py:473} INFO - Spark-Submit cmd: spark-submit --master spark://spark:7077 --name arrow-spark --deploy-mode client /opt/***/dags/spark_job.py
[2024-11-18T17:50:21.834+0000] {spark_submit.py:634} INFO - 24/11/18 17:50:46 INFO SparkContext: Running Spark version 3.5.3
[2024-11-18T17:50:21.866+0000] {spark_submit.py:634} INFO - 24/11/18 17:50:21 INFO SparkContext: OS info Linux, 5.15.153.1-microsoft-standard-WSL2, amd64
[2024-11-18T17:50:21.868+0000] {spark_submit.py:634} INFO - 24/11/18 17:50:21 INFO SparkContext: Java version 17.0.12
[2024-11-18T17:50:22.616+0000] {spark_submit.py:634} INFO - 24/11/18 17:50:22 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-11-18T17:50:57.228+0000] {job.py:218} ERROR - Job heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/jobs/job.py", line 192, in heartbeat
    self._merge_from(Job._fetch_from_db(self, session))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/api_internal/internal_api_call.py", line 115, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/retries.py", line 89, in wrapped_function
    for attempt in run_with_db_retries(max_retries=retries, logger=logger, **retry_kwargs):
  File "/home/airflow/.local/lib/python3.11/site-packages/tenacity/__init__.py", line 443, in __iter__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/tenacity/__init__.py", line 418, in exc_check
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/tenacity/__init__.py", line 185, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/retries.py", line 98, in wrapped_function
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/jobs/job.py", line 316, in _fetch_from_db
    session.merge(job)
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 3056, in merge
    return self._merge(
           ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 3136, in _merge
    merged = self.get(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2853, in get
    return self._get_impl(
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2975, in _get_impl
    return db_load_fn(
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/future/engine.py", line 412, in connect
    return super(Engine, self).connect()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
           ^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-11-18T17:50:59.084+0000] {job.py:226} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
[2024-11-18T17:51:02.210+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:02 INFO ResourceUtils: ==============================================================
[2024-11-18T17:51:02.218+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:02 INFO ResourceUtils: No custom resources configured for spark.driver.
[2024-11-18T17:51:02.226+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:02 INFO ResourceUtils: ==============================================================
[2024-11-18T17:51:02.231+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:02 INFO SparkContext: Submitted application: Airflow Spark Job
[2024-11-18T17:51:02.693+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:02 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2024-11-18T17:51:02.775+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:02 INFO ResourceProfile: Limiting resource is cpu
[2024-11-18T17:51:02.781+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:02 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2024-11-18T17:51:03.240+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:03 INFO SecurityManager: Changing view acls to: ***
[2024-11-18T17:51:03.257+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:03 INFO SecurityManager: Changing modify acls to: ***
[2024-11-18T17:51:03.301+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:03 INFO SecurityManager: Changing view acls groups to:
[2024-11-18T17:51:03.311+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:03 INFO SecurityManager: Changing modify acls groups to:
[2024-11-18T17:51:03.317+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:03 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: ***; groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY
[2024-11-18T17:51:06.893+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:06 INFO Utils: Successfully started service 'sparkDriver' on port 33415.
[2024-11-18T17:51:07.644+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:07 INFO SparkEnv: Registering MapOutputTracker
[2024-11-18T17:51:08.130+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:08 INFO SparkEnv: Registering BlockManagerMaster
[2024-11-18T17:51:08.323+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:08 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2024-11-18T17:51:08.325+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:08 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2024-11-18T17:51:08.429+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:08 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2024-11-18T17:51:08.620+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:08 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-ac46350e-61df-495a-93c3-b767b47a6f58
[2024-11-18T17:51:09.046+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:09 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2024-11-18T17:51:09.593+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:09 INFO SparkEnv: Registering OutputCommitCoordinator
[2024-11-18T17:51:18.445+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:18 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2024-11-18T17:51:20.780+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:20 WARN Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
[2024-11-18T17:51:20.811+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:20 WARN Utils: Service 'SparkUI' could not bind on port 4041. Attempting port 4042.
[2024-11-18T17:51:20.818+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:20 WARN Utils: Service 'SparkUI' could not bind on port 4042. Attempting port 4043.
[2024-11-18T17:51:20.831+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:20 WARN Utils: Service 'SparkUI' could not bind on port 4043. Attempting port 4044.
[2024-11-18T17:51:20.850+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:20 WARN Utils: Service 'SparkUI' could not bind on port 4044. Attempting port 4045.
[2024-11-18T17:51:20.851+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:20 WARN Utils: Service 'SparkUI' could not bind on port 4045. Attempting port 4046.
[2024-11-18T17:51:20.857+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:20 WARN Utils: Service 'SparkUI' could not bind on port 4046. Attempting port 4047.
[2024-11-18T17:51:21.029+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:21 INFO Utils: Successfully started service 'SparkUI' on port 4047.
[2024-11-18T17:51:22.341+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:22 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2024-11-18T17:51:22.987+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:22 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master spark:7077
[2024-11-18T17:51:22.988+0000] {spark_submit.py:634} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2024-11-18T17:51:23.002+0000] {spark_submit.py:634} INFO - at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:56)
[2024-11-18T17:51:23.013+0000] {spark_submit.py:634} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
[2024-11-18T17:51:23.022+0000] {spark_submit.py:634} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2024-11-18T17:51:23.054+0000] {spark_submit.py:634} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
[2024-11-18T17:51:23.055+0000] {spark_submit.py:634} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
[2024-11-18T17:51:23.061+0000] {spark_submit.py:634} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:108)
[2024-11-18T17:51:23.066+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[2024-11-18T17:51:23.083+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2024-11-18T17:51:23.084+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2024-11-18T17:51:23.091+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2024-11-18T17:51:23.093+0000] {spark_submit.py:634} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2024-11-18T17:51:23.095+0000] {spark_submit.py:634} INFO - Caused by: java.io.IOException: Failed to connect to spark/172.19.0.4:7077
[2024-11-18T17:51:23.100+0000] {spark_submit.py:634} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:294)
[2024-11-18T17:51:23.110+0000] {spark_submit.py:634} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:214)
[2024-11-18T17:51:23.115+0000] {spark_submit.py:634} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:226)
[2024-11-18T17:51:23.126+0000] {spark_submit.py:634} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2024-11-18T17:51:23.132+0000] {spark_submit.py:634} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2024-11-18T17:51:23.138+0000] {spark_submit.py:634} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2024-11-18T17:51:23.141+0000] {spark_submit.py:634} INFO - ... 4 more
[2024-11-18T17:51:23.144+0000] {spark_submit.py:634} INFO - Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: spark/172.19.0.4:7077
[2024-11-18T17:51:23.151+0000] {spark_submit.py:634} INFO - Caused by: java.net.ConnectException: Connection refused
[2024-11-18T17:51:23.157+0000] {spark_submit.py:634} INFO - at java.base/sun.nio.ch.Net.pollConnect(Native Method)
[2024-11-18T17:51:23.161+0000] {spark_submit.py:634} INFO - at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
[2024-11-18T17:51:23.171+0000] {spark_submit.py:634} INFO - at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:946)
[2024-11-18T17:51:23.173+0000] {spark_submit.py:634} INFO - at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
[2024-11-18T17:51:23.174+0000] {spark_submit.py:634} INFO - at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
[2024-11-18T17:51:23.181+0000] {spark_submit.py:634} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
[2024-11-18T17:51:23.182+0000] {spark_submit.py:634} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
[2024-11-18T17:51:23.183+0000] {spark_submit.py:634} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
[2024-11-18T17:51:23.183+0000] {spark_submit.py:634} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
[2024-11-18T17:51:23.185+0000] {spark_submit.py:634} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[2024-11-18T17:51:23.186+0000] {spark_submit.py:634} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2024-11-18T17:51:23.187+0000] {spark_submit.py:634} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2024-11-18T17:51:23.187+0000] {spark_submit.py:634} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2024-11-18T17:51:42.319+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:42 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2024-11-18T17:51:42.327+0000] {spark_submit.py:634} INFO - 24/11/18 17:51:42 WARN StandaloneAppClient$ClientEndpoint: Failed to connect to master spark:7077
[2024-11-18T17:51:42.328+0000] {spark_submit.py:634} INFO - org.apache.spark.SparkException: Exception thrown in awaitResult:
[2024-11-18T17:51:42.328+0000] {spark_submit.py:634} INFO - at org.apache.spark.util.SparkThreadUtils$.awaitResult(SparkThreadUtils.scala:56)
[2024-11-18T17:51:42.329+0000] {spark_submit.py:634} INFO - at org.apache.spark.util.ThreadUtils$.awaitResult(ThreadUtils.scala:310)
[2024-11-18T17:51:42.329+0000] {spark_submit.py:634} INFO - at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:75)
[2024-11-18T17:51:42.329+0000] {spark_submit.py:634} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:102)
[2024-11-18T17:51:42.330+0000] {spark_submit.py:634} INFO - at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:110)
[2024-11-18T17:51:42.330+0000] {spark_submit.py:634} INFO - at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anon$1.run(StandaloneAppClient.scala:108)
[2024-11-18T17:51:42.330+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
[2024-11-18T17:51:42.331+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[2024-11-18T17:51:42.332+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2024-11-18T17:51:42.332+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2024-11-18T17:51:42.332+0000] {spark_submit.py:634} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2024-11-18T17:51:42.333+0000] {spark_submit.py:634} INFO - Caused by: java.io.IOException: Failed to connect to spark/172.19.0.4:7077
[2024-11-18T17:51:42.335+0000] {spark_submit.py:634} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:294)
[2024-11-18T17:51:42.336+0000] {spark_submit.py:634} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:214)
[2024-11-18T17:51:42.338+0000] {spark_submit.py:634} INFO - at org.apache.spark.network.client.TransportClientFactory.createClient(TransportClientFactory.java:226)
[2024-11-18T17:51:42.338+0000] {spark_submit.py:634} INFO - at org.apache.spark.rpc.netty.NettyRpcEnv.createClient(NettyRpcEnv.scala:204)
[2024-11-18T17:51:42.339+0000] {spark_submit.py:634} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:202)
[2024-11-18T17:51:42.340+0000] {spark_submit.py:634} INFO - at org.apache.spark.rpc.netty.Outbox$$anon$1.call(Outbox.scala:198)
[2024-11-18T17:51:42.340+0000] {spark_submit.py:634} INFO - ... 4 more
[2024-11-18T17:51:42.342+0000] {spark_submit.py:634} INFO - Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: spark/172.19.0.4:7077
[2024-11-18T17:51:42.343+0000] {spark_submit.py:634} INFO - Caused by: java.net.ConnectException: Connection refused
[2024-11-18T17:51:42.343+0000] {spark_submit.py:634} INFO - at java.base/sun.nio.ch.Net.pollConnect(Native Method)
[2024-11-18T17:51:42.344+0000] {spark_submit.py:634} INFO - at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
[2024-11-18T17:51:42.344+0000] {spark_submit.py:634} INFO - at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:946)
[2024-11-18T17:51:42.345+0000] {spark_submit.py:634} INFO - at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
[2024-11-18T17:51:42.345+0000] {spark_submit.py:634} INFO - at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
[2024-11-18T17:51:42.346+0000] {spark_submit.py:634} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
[2024-11-18T17:51:42.346+0000] {spark_submit.py:634} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
[2024-11-18T17:51:42.346+0000] {spark_submit.py:634} INFO - at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
[2024-11-18T17:51:42.347+0000] {spark_submit.py:634} INFO - at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
[2024-11-18T17:51:42.347+0000] {spark_submit.py:634} INFO - at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
[2024-11-18T17:51:42.348+0000] {spark_submit.py:634} INFO - at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
[2024-11-18T17:51:42.348+0000] {spark_submit.py:634} INFO - at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
[2024-11-18T17:51:42.349+0000] {spark_submit.py:634} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2024-11-18T17:52:02.657+0000] {spark_submit.py:634} INFO - 24/11/18 17:52:02 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark:7077...
[2024-11-18T17:52:03.140+0000] {spark_submit.py:634} INFO - 24/11/18 17:52:03 INFO TransportClientFactory: Successfully created connection to spark/172.19.0.8:7077 after 4 ms (0 ms spent in bootstraps)
[2024-11-18T17:52:04.361+0000] {spark_submit.py:634} INFO - 24/11/18 17:52:04 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20241118175204-0007
[2024-11-18T17:52:04.435+0000] {spark_submit.py:634} INFO - 24/11/18 17:52:04 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 40173.
[2024-11-18T17:52:04.437+0000] {spark_submit.py:634} INFO - 24/11/18 17:52:04 INFO NettyBlockTransferService: Server created on 3fa30a842a1c:40173
[2024-11-18T17:52:04.446+0000] {spark_submit.py:634} INFO - 24/11/18 17:52:04 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2024-11-18T17:52:04.459+0000] {spark_submit.py:634} INFO - 24/11/18 17:52:04 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 3fa30a842a1c, 40173, None)
[2024-11-18T17:52:04.467+0000] {spark_submit.py:634} INFO - 24/11/18 17:52:04 INFO BlockManagerMasterEndpoint: Registering block manager 3fa30a842a1c:40173 with 434.4 MiB RAM, BlockManagerId(driver, 3fa30a842a1c, 40173, None)
[2024-11-18T17:52:04.480+0000] {spark_submit.py:634} INFO - 24/11/18 17:52:04 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 3fa30a842a1c, 40173, None)
[2024-11-18T17:52:04.483+0000] {spark_submit.py:634} INFO - 24/11/18 17:52:04 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 3fa30a842a1c, 40173, None)
[2024-11-18T17:52:07.832+0000] {spark_submit.py:634} INFO - 24/11/18 17:52:07 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2024-11-18T17:52:44.729+0000] {spark_submit.py:634} INFO - 24/11/18 17:52:44 INFO AsyncEventQueue: Process of event SparkListenerExecutorMetricsUpdate(driver,WrappedArray(),Map((-1,-1) -> org.apache.spark.executor.ExecutorMetrics@27cdc70f)) by listener AppStatusListener took 6.269638589s.
[2024-11-18T17:52:57.206+0000] {job.py:226} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
[2024-11-18T17:54:24.480+0000] {job.py:226} ERROR - Job heartbeat failed with error. Scheduler is in unhealthy state
[2024-11-18T17:54:40.186+0000] {spark_submit.py:634} INFO - 24/11/18 17:54:39 INFO AsyncEventQueue: Process of event SparkListenerExecutorMetricsUpdate(driver,WrappedArray(),Map((-1,-1) -> org.apache.spark.executor.ExecutorMetrics@1d259920)) by listener AppStatusListener took 2.458025408s.
[2024-11-18T17:54:44.661+0000] {spark_submit.py:634} INFO - 24/11/18 17:54:43 INFO AsyncEventQueue: Process of event SparkListenerExecutorMetricsUpdate(driver,WrappedArray(),Map((-1,-1) -> org.apache.spark.executor.ExecutorMetrics@5499d034)) by listener AppStatusListener took 1.03183774s.
[2024-11-18T17:54:49.068+0000] {spark_submit.py:634} INFO - 24/11/18 17:54:49 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2024-11-18T17:54:49.226+0000] {spark_submit.py:634} INFO - 24/11/18 17:54:49 INFO SharedState: Warehouse path is 'file:/app/spark-warehouse'.
[2024-11-18T17:55:13.521+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:13 INFO CodeGenerator: Code generated in 1309.4559 ms
[2024-11-18T17:55:13.593+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:13 INFO SparkContext: Starting job: showString at NativeMethodAccessorImpl.java:0
[2024-11-18T17:55:13.669+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:13 INFO DAGScheduler: Got job 0 (showString at NativeMethodAccessorImpl.java:0) with 1 output partitions
[2024-11-18T17:55:13.671+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:13 INFO DAGScheduler: Final stage: ResultStage 0 (showString at NativeMethodAccessorImpl.java:0)
[2024-11-18T17:55:13.673+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:13 INFO DAGScheduler: Parents of final stage: List()
[2024-11-18T17:55:13.676+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:13 INFO DAGScheduler: Missing parents: List()
[2024-11-18T17:55:13.690+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:13 INFO DAGScheduler: Submitting ResultStage 0 (MapPartitionsRDD[6] at showString at NativeMethodAccessorImpl.java:0), which has no missing parents
[2024-11-18T17:55:14.242+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:14 INFO MemoryStore: Block broadcast_0 stored as values in memory (estimated size 13.1 KiB, free 434.4 MiB)
[2024-11-18T17:55:14.410+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:14 INFO MemoryStore: Block broadcast_0_piece0 stored as bytes in memory (estimated size 6.8 KiB, free 434.4 MiB)
[2024-11-18T17:55:14.435+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:14 INFO BlockManagerInfo: Added broadcast_0_piece0 in memory on 3fa30a842a1c:40173 (size: 6.8 KiB, free: 434.4 MiB)
[2024-11-18T17:55:14.446+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:14 INFO SparkContext: Created broadcast 0 from broadcast at DAGScheduler.scala:1585
[2024-11-18T17:55:14.658+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:14 INFO DAGScheduler: Submitting 1 missing tasks from ResultStage 0 (MapPartitionsRDD[6] at showString at NativeMethodAccessorImpl.java:0) (first 15 tasks are for partitions Vector(0))
[2024-11-18T17:55:14.666+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:14 INFO TaskSchedulerImpl: Adding task set 0.0 with 1 tasks resource profile 0
[2024-11-18T17:55:29.777+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:29 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2024-11-18T17:55:44.771+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:44 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2024-11-18T17:55:58.330+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:58 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20241118175204-0007/0 on worker-20241118175528-172.19.0.10-35337 (172.19.0.10:35337) with 1 core(s)
[2024-11-18T17:55:58.332+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:58 INFO StandaloneSchedulerBackend: Granted executor ID app-20241118175204-0007/0 on hostPort 172.19.0.10:35337 with 1 core(s), 1024.0 MiB RAM
[2024-11-18T17:55:58.335+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:58 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20241118175204-0007/1 on worker-20241118175528-172.19.0.6-33793 (172.19.0.6:33793) with 1 core(s)
[2024-11-18T17:55:58.337+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:58 INFO StandaloneSchedulerBackend: Granted executor ID app-20241118175204-0007/1 on hostPort 172.19.0.6:33793 with 1 core(s), 1024.0 MiB RAM
[2024-11-18T17:55:58.404+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:58 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20241118175204-0007/1 is now RUNNING
[2024-11-18T17:55:58.405+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:58 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20241118175204-0007/0 is now RUNNING
[2024-11-18T17:55:59.773+0000] {spark_submit.py:634} INFO - 24/11/18 17:55:59 WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources
[2024-11-18T17:56:03.405+0000] {spark_submit.py:634} INFO - 24/11/18 17:56:03 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Registered executor NettyRpcEndpointRef(spark-client://Executor) (172.19.0.6:42120) with ID 1,  ResourceProfileId 0
[2024-11-18T17:56:03.570+0000] {spark_submit.py:634} INFO - 24/11/18 17:56:03 INFO BlockManagerMasterEndpoint: Registering block manager 172.19.0.6:44855 with 434.4 MiB RAM, BlockManagerId(1, 172.19.0.6, 44855, None)
[2024-11-18T17:56:03.675+0000] {spark_submit.py:634} INFO - 24/11/18 17:56:03 INFO TaskSetManager: Starting task 0.0 in stage 0.0 (TID 0) (172.19.0.6, executor 1, partition 0, PROCESS_LOCAL, 9122 bytes)
[2024-11-18T17:56:03.691+0000] {spark_submit.py:634} INFO - 24/11/18 17:56:03 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Registered executor NettyRpcEndpointRef(spark-client://Executor) (172.19.0.10:32958) with ID 0,  ResourceProfileId 0
[2024-11-18T17:56:03.869+0000] {spark_submit.py:634} INFO - 24/11/18 17:56:03 INFO BlockManagerMasterEndpoint: Registering block manager 172.19.0.10:39193 with 434.4 MiB RAM, BlockManagerId(0, 172.19.0.10, 39193, None)
[2024-11-18T17:56:03.936+0000] {spark_submit.py:634} INFO - 24/11/18 17:56:03 WARN TaskSetManager: Lost task 0.0 in stage 0.0 (TID 0) (172.19.0.6 executor 1): java.io.InvalidClassException: org.apache.spark.scheduler.Task; local class incompatible: stream classdesc serialVersionUID = -6188971942555435033, local class serialVersionUID = 553100815431272095
[2024-11-18T17:56:03.946+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:597)
[2024-11-18T17:56:03.947+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2051)
[2024-11-18T17:56:03.951+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1898)
[2024-11-18T17:56:03.952+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2051)
[2024-11-18T17:56:03.953+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1898)
[2024-11-18T17:56:03.956+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2224)
[2024-11-18T17:56:03.960+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1733)
[2024-11-18T17:56:03.963+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:509)
[2024-11-18T17:56:03.968+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:467)
[2024-11-18T17:56:03.969+0000] {spark_submit.py:634} INFO - at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:87)
[2024-11-18T17:56:03.990+0000] {spark_submit.py:634} INFO - at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:129)
[2024-11-18T17:56:04.001+0000] {spark_submit.py:634} INFO - at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:579)
[2024-11-18T17:56:04.018+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2024-11-18T17:56:04.034+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2024-11-18T17:56:04.051+0000] {spark_submit.py:634} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2024-11-18T17:56:04.053+0000] {spark_submit.py:634} INFO - 
[2024-11-18T17:56:04.069+0000] {spark_submit.py:634} INFO - 24/11/18 17:56:03 INFO TaskSetManager: Starting task 0.1 in stage 0.0 (TID 1) (172.19.0.6, executor 1, partition 0, PROCESS_LOCAL, 9122 bytes)
[2024-11-18T17:56:04.089+0000] {spark_submit.py:634} INFO - 24/11/18 17:56:04 INFO TaskSetManager: Lost task 0.1 in stage 0.0 (TID 1) on 172.19.0.6, executor 1: java.io.InvalidClassException (org.apache.spark.scheduler.Task; local class incompatible: stream classdesc serialVersionUID = -6188971942555435033, local class serialVersionUID = 553100815431272095) [duplicate 1]
[2024-11-18T17:56:04.105+0000] {spark_submit.py:634} INFO - 24/11/18 17:56:04 INFO TaskSetManager: Starting task 0.2 in stage 0.0 (TID 2) (172.19.0.10, executor 0, partition 0, PROCESS_LOCAL, 9122 bytes)
[2024-11-18T17:56:04.403+0000] {spark_submit.py:634} INFO - 24/11/18 17:56:04 INFO TaskSetManager: Lost task 0.2 in stage 0.0 (TID 2) on 172.19.0.10, executor 0: java.io.InvalidClassException (org.apache.spark.scheduler.Task; local class incompatible: stream classdesc serialVersionUID = -6188971942555435033, local class serialVersionUID = 553100815431272095) [duplicate 2]
[2024-11-18T17:56:04.416+0000] {spark_submit.py:634} INFO - 24/11/18 17:56:04 INFO TaskSetManager: Starting task 0.3 in stage 0.0 (TID 3) (172.19.0.10, executor 0, partition 0, PROCESS_LOCAL, 9122 bytes)
[2024-11-18T17:56:04.462+0000] {spark_submit.py:634} INFO - 24/11/18 17:56:04 INFO TaskSetManager: Lost task 0.3 in stage 0.0 (TID 3) on 172.19.0.10, executor 0: java.io.InvalidClassException (org.apache.spark.scheduler.Task; local class incompatible: stream classdesc serialVersionUID = -6188971942555435033, local class serialVersionUID = 553100815431272095) [duplicate 3]
[2024-11-18T17:56:04.477+0000] {spark_submit.py:634} INFO - 24/11/18 17:56:04 ERROR TaskSetManager: Task 0 in stage 0.0 failed 4 times; aborting job
[2024-11-18T17:56:04.489+0000] {spark_submit.py:634} INFO - 24/11/18 17:56:04 INFO TaskSchedulerImpl: Removed TaskSet 0.0, whose tasks have all completed, from pool
[2024-11-18T17:56:04.491+0000] {spark_submit.py:634} INFO - 24/11/18 17:56:04 INFO TaskSchedulerImpl: Cancelling stage 0
[2024-11-18T17:56:04.501+0000] {spark_submit.py:634} INFO - 24/11/18 17:56:04 INFO TaskSchedulerImpl: Killing all running tasks in stage 0: Stage cancelled: Job aborted due to stage failure: Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 3) (172.19.0.10 executor 0): java.io.InvalidClassException: org.apache.spark.scheduler.Task; local class incompatible: stream classdesc serialVersionUID = -6188971942555435033, local class serialVersionUID = 553100815431272095
[2024-11-18T17:56:04.503+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:597)
[2024-11-18T17:56:04.504+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2051)
[2024-11-18T17:56:04.505+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1898)
[2024-11-18T17:56:04.505+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2051)
[2024-11-18T17:56:04.506+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1898)
[2024-11-18T17:56:04.506+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2224)
[2024-11-18T17:56:04.507+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1733)
[2024-11-18T17:56:04.508+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:509)
[2024-11-18T17:56:04.513+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:467)
[2024-11-18T17:56:04.522+0000] {spark_submit.py:634} INFO - at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:87)
[2024-11-18T17:56:04.530+0000] {spark_submit.py:634} INFO - at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:129)
[2024-11-18T17:56:04.531+0000] {spark_submit.py:634} INFO - at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:579)
[2024-11-18T17:56:04.533+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2024-11-18T17:56:04.535+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2024-11-18T17:56:04.537+0000] {spark_submit.py:634} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2024-11-18T17:56:04.539+0000] {spark_submit.py:634} INFO - 
[2024-11-18T17:56:04.541+0000] {spark_submit.py:634} INFO - Driver stacktrace:
[2024-11-18T17:56:04.542+0000] {spark_submit.py:634} INFO - 24/11/18 17:56:04 INFO DAGScheduler: ResultStage 0 (showString at NativeMethodAccessorImpl.java:0) failed in 50.700 s due to Job aborted due to stage failure: Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 3) (172.19.0.10 executor 0): java.io.InvalidClassException: org.apache.spark.scheduler.Task; local class incompatible: stream classdesc serialVersionUID = -6188971942555435033, local class serialVersionUID = 553100815431272095
[2024-11-18T17:56:04.542+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:597)
[2024-11-18T17:56:04.543+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2051)
[2024-11-18T17:56:04.544+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1898)
[2024-11-18T17:56:04.545+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2051)
[2024-11-18T17:56:04.546+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1898)
[2024-11-18T17:56:04.547+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2224)
[2024-11-18T17:56:04.549+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1733)
[2024-11-18T17:56:04.564+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:509)
[2024-11-18T17:56:04.565+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:467)
[2024-11-18T17:56:04.566+0000] {spark_submit.py:634} INFO - at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:87)
[2024-11-18T17:56:04.566+0000] {spark_submit.py:634} INFO - at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:129)
[2024-11-18T17:56:04.567+0000] {spark_submit.py:634} INFO - at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:579)
[2024-11-18T17:56:04.567+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2024-11-18T17:56:04.567+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2024-11-18T17:56:04.568+0000] {spark_submit.py:634} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2024-11-18T17:56:04.569+0000] {spark_submit.py:634} INFO - 
[2024-11-18T17:56:04.569+0000] {spark_submit.py:634} INFO - Driver stacktrace:
[2024-11-18T17:56:04.570+0000] {spark_submit.py:634} INFO - 24/11/18 17:56:04 INFO DAGScheduler: Job 0 failed: showString at NativeMethodAccessorImpl.java:0, took 50.903814 s
[2024-11-18T17:56:04.983+0000] {spark_submit.py:634} INFO - Traceback (most recent call last):
[2024-11-18T17:56:04.984+0000] {spark_submit.py:634} INFO - File "/opt/***/dags/spark_job.py", line 16, in <module>
[2024-11-18T17:56:04.986+0000] {spark_submit.py:634} INFO - df.show()
[2024-11-18T17:56:04.986+0000] {spark_submit.py:634} INFO - File "/home/***/.local/lib/python3.11/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/dataframe.py", line 947, in show
[2024-11-18T17:56:04.987+0000] {spark_submit.py:634} INFO - File "/home/***/.local/lib/python3.11/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/dataframe.py", line 965, in _show_string
[2024-11-18T17:56:04.988+0000] {spark_submit.py:634} INFO - File "/home/***/.local/lib/python3.11/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
[2024-11-18T17:56:04.989+0000] {spark_submit.py:634} INFO - File "/home/***/.local/lib/python3.11/site-packages/pyspark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 179, in deco
[2024-11-18T17:56:04.989+0000] {spark_submit.py:634} INFO - File "/home/***/.local/lib/python3.11/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/protocol.py", line 326, in get_return_value
[2024-11-18T17:56:04.990+0000] {spark_submit.py:634} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling o41.showString.
[2024-11-18T17:56:04.991+0000] {spark_submit.py:634} INFO - : org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 0.0 failed 4 times, most recent failure: Lost task 0.3 in stage 0.0 (TID 3) (172.19.0.10 executor 0): java.io.InvalidClassException: org.apache.spark.scheduler.Task; local class incompatible: stream classdesc serialVersionUID = -6188971942555435033, local class serialVersionUID = 553100815431272095
[2024-11-18T17:56:04.991+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:597)
[2024-11-18T17:56:04.991+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2051)
[2024-11-18T17:56:04.991+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1898)
[2024-11-18T17:56:04.992+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2051)
[2024-11-18T17:56:04.992+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1898)
[2024-11-18T17:56:04.993+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2224)
[2024-11-18T17:56:04.993+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1733)
[2024-11-18T17:56:04.993+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:509)
[2024-11-18T17:56:04.994+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:467)
[2024-11-18T17:56:04.994+0000] {spark_submit.py:634} INFO - at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:87)
[2024-11-18T17:56:04.994+0000] {spark_submit.py:634} INFO - at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:129)
[2024-11-18T17:56:04.994+0000] {spark_submit.py:634} INFO - at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:579)
[2024-11-18T17:56:04.995+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2024-11-18T17:56:04.995+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2024-11-18T17:56:04.995+0000] {spark_submit.py:634} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2024-11-18T17:56:04.995+0000] {spark_submit.py:634} INFO - 
[2024-11-18T17:56:04.996+0000] {spark_submit.py:634} INFO - Driver stacktrace:
[2024-11-18T17:56:04.996+0000] {spark_submit.py:634} INFO - at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2856)
[2024-11-18T17:56:04.996+0000] {spark_submit.py:634} INFO - at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2792)
[2024-11-18T17:56:04.997+0000] {spark_submit.py:634} INFO - at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2791)
[2024-11-18T17:56:04.997+0000] {spark_submit.py:634} INFO - at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
[2024-11-18T17:56:04.998+0000] {spark_submit.py:634} INFO - at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
[2024-11-18T17:56:04.998+0000] {spark_submit.py:634} INFO - at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
[2024-11-18T17:56:04.999+0000] {spark_submit.py:634} INFO - at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2791)
[2024-11-18T17:56:04.999+0000] {spark_submit.py:634} INFO - at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1247)
[2024-11-18T17:56:05.000+0000] {spark_submit.py:634} INFO - at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1247)
[2024-11-18T17:56:05.000+0000] {spark_submit.py:634} INFO - at scala.Option.foreach(Option.scala:407)
[2024-11-18T17:56:05.000+0000] {spark_submit.py:634} INFO - at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1247)
[2024-11-18T17:56:05.001+0000] {spark_submit.py:634} INFO - at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:3060)
[2024-11-18T17:56:05.001+0000] {spark_submit.py:634} INFO - at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2994)
[2024-11-18T17:56:05.002+0000] {spark_submit.py:634} INFO - at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2983)
[2024-11-18T17:56:05.002+0000] {spark_submit.py:634} INFO - at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
[2024-11-18T17:56:05.003+0000] {spark_submit.py:634} INFO - at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:989)
[2024-11-18T17:56:05.004+0000] {spark_submit.py:634} INFO - at org.apache.spark.SparkContext.runJob(SparkContext.scala:2393)
[2024-11-18T17:56:05.005+0000] {spark_submit.py:634} INFO - at org.apache.spark.SparkContext.runJob(SparkContext.scala:2414)
[2024-11-18T17:56:05.005+0000] {spark_submit.py:634} INFO - at org.apache.spark.SparkContext.runJob(SparkContext.scala:2433)
[2024-11-18T17:56:05.006+0000] {spark_submit.py:634} INFO - at org.apache.spark.sql.execution.SparkPlan.executeTake(SparkPlan.scala:530)
[2024-11-18T17:56:05.006+0000] {spark_submit.py:634} INFO - at org.apache.spark.sql.execution.SparkPlan.executeTake(SparkPlan.scala:483)
[2024-11-18T17:56:05.007+0000] {spark_submit.py:634} INFO - at org.apache.spark.sql.execution.CollectLimitExec.executeCollect(limit.scala:61)
[2024-11-18T17:56:05.007+0000] {spark_submit.py:634} INFO - at org.apache.spark.sql.Dataset.collectFromPlan(Dataset.scala:4333)
[2024-11-18T17:56:05.008+0000] {spark_submit.py:634} INFO - at org.apache.spark.sql.Dataset.$anonfun$head$1(Dataset.scala:3316)
[2024-11-18T17:56:05.008+0000] {spark_submit.py:634} INFO - at org.apache.spark.sql.Dataset.$anonfun$withAction$2(Dataset.scala:4323)
[2024-11-18T17:56:05.008+0000] {spark_submit.py:634} INFO - at org.apache.spark.sql.execution.QueryExecution$.withInternalError(QueryExecution.scala:546)
[2024-11-18T17:56:05.009+0000] {spark_submit.py:634} INFO - at org.apache.spark.sql.Dataset.$anonfun$withAction$1(Dataset.scala:4321)
[2024-11-18T17:56:05.009+0000] {spark_submit.py:634} INFO - at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$6(SQLExecution.scala:125)
[2024-11-18T17:56:05.009+0000] {spark_submit.py:634} INFO - at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:201)
[2024-11-18T17:56:05.010+0000] {spark_submit.py:634} INFO - at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:108)
[2024-11-18T17:56:05.010+0000] {spark_submit.py:634} INFO - at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:900)
[2024-11-18T17:56:05.011+0000] {spark_submit.py:634} INFO - at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:66)
[2024-11-18T17:56:05.011+0000] {spark_submit.py:634} INFO - at org.apache.spark.sql.Dataset.withAction(Dataset.scala:4321)
[2024-11-18T17:56:05.011+0000] {spark_submit.py:634} INFO - at org.apache.spark.sql.Dataset.head(Dataset.scala:3316)
[2024-11-18T17:56:05.012+0000] {spark_submit.py:634} INFO - at org.apache.spark.sql.Dataset.take(Dataset.scala:3539)
[2024-11-18T17:56:05.014+0000] {spark_submit.py:634} INFO - at org.apache.spark.sql.Dataset.getRows(Dataset.scala:280)
[2024-11-18T17:56:05.015+0000] {spark_submit.py:634} INFO - at org.apache.spark.sql.Dataset.showString(Dataset.scala:315)
[2024-11-18T17:56:05.015+0000] {spark_submit.py:634} INFO - at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2024-11-18T17:56:05.016+0000] {spark_submit.py:634} INFO - at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2024-11-18T17:56:05.016+0000] {spark_submit.py:634} INFO - at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2024-11-18T17:56:05.017+0000] {spark_submit.py:634} INFO - at java.base/java.lang.reflect.Method.invoke(Method.java:569)
[2024-11-18T17:56:05.018+0000] {spark_submit.py:634} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2024-11-18T17:56:05.018+0000] {spark_submit.py:634} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2024-11-18T17:56:05.019+0000] {spark_submit.py:634} INFO - at py4j.Gateway.invoke(Gateway.java:282)
[2024-11-18T17:56:05.019+0000] {spark_submit.py:634} INFO - at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2024-11-18T17:56:05.020+0000] {spark_submit.py:634} INFO - at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2024-11-18T17:56:05.020+0000] {spark_submit.py:634} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2024-11-18T17:56:05.020+0000] {spark_submit.py:634} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2024-11-18T17:56:05.020+0000] {spark_submit.py:634} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2024-11-18T17:56:05.021+0000] {spark_submit.py:634} INFO - Caused by: java.io.InvalidClassException: org.apache.spark.scheduler.Task; local class incompatible: stream classdesc serialVersionUID = -6188971942555435033, local class serialVersionUID = 553100815431272095
[2024-11-18T17:56:05.021+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:597)
[2024-11-18T17:56:05.021+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2051)
[2024-11-18T17:56:05.022+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1898)
[2024-11-18T17:56:05.022+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2051)
[2024-11-18T17:56:05.022+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1898)
[2024-11-18T17:56:05.022+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2224)
[2024-11-18T17:56:05.023+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1733)
[2024-11-18T17:56:05.023+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:509)
[2024-11-18T17:56:05.023+0000] {spark_submit.py:634} INFO - at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:467)
[2024-11-18T17:56:05.023+0000] {spark_submit.py:634} INFO - at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:87)
[2024-11-18T17:56:05.024+0000] {spark_submit.py:634} INFO - at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:129)
[2024-11-18T17:56:05.024+0000] {spark_submit.py:634} INFO - at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:579)
[2024-11-18T17:56:05.024+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[2024-11-18T17:56:05.024+0000] {spark_submit.py:634} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[2024-11-18T17:56:05.025+0000] {spark_submit.py:634} INFO - ... 1 more
[2024-11-18T17:56:05.025+0000] {spark_submit.py:634} INFO - 
[2024-11-18T17:56:05.426+0000] {spark_submit.py:634} INFO - 24/11/18 17:56:05 INFO SparkContext: Invoking stop() from shutdown hook
[2024-11-18T17:56:05.427+0000] {spark_submit.py:634} INFO - 24/11/18 17:56:05 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2024-11-18T17:56:05.448+0000] {spark_submit.py:634} INFO - 24/11/18 17:56:05 INFO SparkUI: Stopped Spark web UI at http://3fa30a842a1c:4047
[2024-11-18T17:56:05.453+0000] {spark_submit.py:634} INFO - 24/11/18 17:56:05 INFO StandaloneSchedulerBackend: Shutting down all executors
[2024-11-18T17:56:05.454+0000] {spark_submit.py:634} INFO - 24/11/18 17:56:05 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Asking each executor to shut down
[2024-11-18T17:56:05.525+0000] {spark_submit.py:634} INFO - 24/11/18 17:56:05 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2024-11-18T17:56:05.652+0000] {spark_submit.py:634} INFO - 24/11/18 17:56:05 INFO MemoryStore: MemoryStore cleared
[2024-11-18T17:56:05.654+0000] {spark_submit.py:634} INFO - 24/11/18 17:56:05 INFO BlockManager: BlockManager stopped
[2024-11-18T17:56:05.664+0000] {spark_submit.py:634} INFO - 24/11/18 17:56:05 INFO BlockManagerMaster: BlockManagerMaster stopped
[2024-11-18T17:56:05.675+0000] {spark_submit.py:634} INFO - 24/11/18 17:56:05 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2024-11-18T17:56:05.712+0000] {spark_submit.py:634} INFO - 24/11/18 17:56:05 INFO SparkContext: Successfully stopped SparkContext
[2024-11-18T17:56:05.714+0000] {spark_submit.py:634} INFO - 24/11/18 17:56:05 INFO ShutdownHookManager: Shutdown hook called
[2024-11-18T17:56:05.723+0000] {spark_submit.py:634} INFO - 24/11/18 17:56:05 INFO ShutdownHookManager: Deleting directory /tmp/spark-b9d79f5a-ccb3-47b6-8ad1-bdf4cc1188e3/pyspark-898138cb-51fa-4868-b0c1-a9d0718175c0
[2024-11-18T17:56:05.728+0000] {spark_submit.py:634} INFO - 24/11/18 17:56:05 INFO ShutdownHookManager: Deleting directory /tmp/spark-b9d79f5a-ccb3-47b6-8ad1-bdf4cc1188e3
[2024-11-18T17:56:05.754+0000] {spark_submit.py:634} INFO - 24/11/18 17:56:05 INFO ShutdownHookManager: Deleting directory /tmp/spark-5be39cc2-878a-4131-84f0-62145b35e49a
[2024-11-18T17:56:05.882+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-18T17:56:05.962+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 176, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 560, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark:7077 --name arrow-spark --deploy-mode client /opt/***/dags/spark_job.py. Error code is: 1.
[2024-11-18T17:56:05.996+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=spark_dag, task_id=spark_job, run_id=scheduled__2024-11-16T00:00:00+00:00, execution_date=20241116T000000, start_date=20241118T174950, end_date=20241118T175605
[2024-11-18T17:56:06.049+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 659 for task spark_job (Cannot execute: spark-submit --master spark://spark:7077 --name arrow-spark --deploy-mode client /opt/***/dags/spark_job.py. Error code is: 1.; 1681)
[2024-11-18T17:56:06.121+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-11-18T17:56:06.196+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-18T17:56:06.201+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
